In [9]:
import cv2
import matplotlib.pyplot as plt
import imutils
from itertools import combinations
import math
import numpy as np
import datetime
import os
import tensorflow as tf

In [10]:
model = tf.keras.models.load_model("model.h5")

In [11]:
#Load model files and graph
config_file='MobileNetSSD_deploy.prototxt'
frozen_model = 'MobileNetSSD_deploy.caffemodel'
#Create model object
p_model = cv2.dnn_DetectionModel(frozen_model, config_file)

In [14]:
#Specify the Labels
classLabels = ["background", "aeroplane", "bicycle", "bird", "boat",
           "bottle", "bus", "car", "cat", "chair", "cow", "diningtable",
           "dog", "horse", "motorbike", "person", "pottedplant", "sheep",
           "sofa", "train", "tvmonitor"]


In [42]:
cap = cv2.VideoCapture()

labels= ['Anger', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

font_scale = 2
font = cv2.FONT_HERSHEY_PLAIN

def get_index(p):
    p = p.flatten()
    p = p.tolist()
    max = 0
    ind = 0
    for i in range(len(p)):
        if max < p[i]:
            max = p[i]
            print('Max: ', max)
            ind = i
    return ind
        

#set input frame properties
p_model.setInputSize(320,320)
p_model.setInputScale(1.0/127.5)
p_model.setInputMean((127.5,127.5,127.5))
p_model.setInputSwapRB(True)

#Check if the video is opened correctly
if not cap.isOpened():
    cap = cv2.VideoCapture(0)
if not cap.isOpened():
    raise IOError("Cannot Open video")
    
while True:
    ret, frame = cap.read()
    if ret == False:
        cap.release()
        cv.destroyAllWindows()
        break
    ClassIndex, confidence, bbox = p_model.detect(frame, confThreshold = 0.55)
    
     #If no object is detected
    if(len(ClassIndex) == 0):
        cv2.imshow('Video feed', frame)
        
    if(len(ClassIndex)  ==1):
        cv2.rectangle(frame, bbox, (0,255,0), 2)
    
    indices=[]
    
    #If some objects are detected, remove the object if it does not falls within one of the required Labels
    if(len(ClassIndex) != 0):
        ClassIndex = ClassIndex.flatten()
        print(ClassIndex, ClassIndex.shape)
        for i in range(ClassIndex.shape[0]):
            if ClassIndex[i]>80:
                indices.append(i)
                continue
            if classLabels[ClassIndex[i]] not in ["person"]:
                print(classLabels[ClassIndex[i]])
                indices.append(i)
        ClassIndex1 = np.delete(ClassIndex, indices)
        print(ClassIndex1)
        mapped = zip(ClassIndex1.flatten(), confidence.flatten(), bbox)
        
        
        for ob in mapped:
            cv2.rectangle(frame, (ob[2][0], ob[2][1], ob[2][2], ob[2][3]), (0,255,0), 2)
            print(ob[2])
            crop_img = frame[ob[2][1]: ob[2][3], ob[2][0]: ob[2][2]]
            print('Crop Image: ',crop_img.shape)
            if crop_img.shape[0] > 100:
                
                crop_img = cv2.resize(crop_img,(48,48),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
                crop_img = cv2.cvtColor(crop_img, cv2.COLOR_BGR2GRAY)
                print(crop_img.shape)
                crop_img = crop_img.reshape(1,48,48,1)
                prediction = model.predict(crop_img)
                print('prediction: ', prediction)
                ind = get_index(prediction)
                print('index : ', ind)
            cv2.putText(frame, labels[ind], (ob[2][0]+10, ob[2][1]+40), font, fontScale= font_scale, color=(0,255,0), thickness=3) 
            
    cv2.imshow('Video feed', frame)                     
    
    if cv2.waitKey(2) & 0xFF == ord('q'): #close the program on pressing 'q'
        break
        
cap.release()#release input video
cv2.destroyAllWindows()
    

[15] (1,)
[15]
[201 134 432 337]
Crop Image:  (203, 231, 3)
(48, 48)
prediction:  [[2.22191826e-01 4.59094408e-05 3.18135023e-02 9.80066359e-02
  5.29547036e-01 7.40525499e-03 1.10989876e-01]]
Max:  0.22219182550907135
Max:  0.5295470356941223
index :  4
[15] (1,)
[15]
[203 135 428 336]
Crop Image:  (201, 225, 3)
(48, 48)
prediction:  [[1.3830145e-01 1.2009502e-04 1.9711671e-02 1.9063139e-01 4.4111615e-01
  7.7413786e-03 2.0237790e-01]]
Max:  0.13830144703388214
Max:  0.19063138961791992
Max:  0.4411161541938782
index :  4
[15] (1,)
[15]
[204 134 428 337]
Crop Image:  (203, 224, 3)
(48, 48)
prediction:  [[0.12161689 0.00053142 0.02732553 0.16231988 0.48296297 0.00964123
  0.19560203]]
Max:  0.12161688506603241
Max:  0.16231988370418549
Max:  0.482962965965271
index :  4
[15] (1,)
[15]
[205 133 427 337]
Crop Image:  (204, 222, 3)
(48, 48)
prediction:  [[1.00191556e-01 4.16411873e-04 1.99943054e-02 1.74087361e-01
  5.91585875e-01 5.11302752e-03 1.08611450e-01]]
Max:  0.10019155591726303


[15] (1,)
[15]
[208 135 424 336]
Crop Image:  (201, 216, 3)
(48, 48)
prediction:  [[0.14596224 0.00093167 0.02056241 0.24754514 0.40005192 0.01903409
  0.16591252]]
Max:  0.14596223831176758
Max:  0.24754513800144196
Max:  0.40005192160606384
index :  4
[15] (1,)
[15]
[207 137 423 334]
Crop Image:  (197, 216, 3)
(48, 48)
prediction:  [[0.13106678 0.00096844 0.01421673 0.32811522 0.36751252 0.02439768
  0.13372265]]
Max:  0.13106678426265717
Max:  0.32811522483825684
Max:  0.3675125241279602
index :  4
[15] (1,)
[15]
[206 135 425 336]
Crop Image:  (201, 219, 3)
(48, 48)
prediction:  [[8.5247487e-02 1.8246668e-04 1.5211802e-02 3.4492433e-01 4.0706605e-01
  1.5159265e-02 1.3220868e-01]]
Max:  0.08524748682975769
Max:  0.34492433071136475
Max:  0.4070660471916199
index :  4
[15] (1,)
[15]
[204 136 426 335]
Crop Image:  (199, 222, 3)
(48, 48)
prediction:  [[1.5250565e-01 2.6954574e-04 2.3138782e-02 2.2478732e-01 4.8660055e-01
  2.5167713e-02 8.7530479e-02]]
Max:  0.15250565111637115
Max:  0

prediction:  [[2.5476956e-01 2.2070695e-04 1.9730471e-01 6.4607754e-02 4.4785792e-01
  8.3326595e-03 2.6906746e-02]]
Max:  0.25476956367492676
Max:  0.44785791635513306
index :  4
[15] (1,)
[15]
[168  93 453 372]
Crop Image:  (279, 285, 3)
(48, 48)
prediction:  [[3.1509584e-01 3.4343571e-04 2.9963640e-02 4.7922201e-02 5.6336725e-01
  6.4639971e-03 3.6843609e-02]]
Max:  0.31509584188461304
Max:  0.5633672475814819
index :  4
[15] (1,)
[15]
[171  95 451 370]
Crop Image:  (275, 280, 3)
(48, 48)
prediction:  [[3.1854773e-01 6.8630681e-05 1.3330479e-01 5.2035455e-02 3.9434260e-01
  1.1911036e-02 8.9789696e-02]]
Max:  0.31854772567749023
Max:  0.3943426012992859
index :  4
[15] (1,)
[15]
[182  94 442 371]
Crop Image:  (277, 260, 3)
(48, 48)
prediction:  [[8.6557835e-02 9.3462717e-05 3.9604396e-02 1.2510294e-01 7.1854091e-01
  2.3597151e-03 2.7740685e-02]]
Max:  0.08655783534049988
Max:  0.1251029372215271
Max:  0.7185409069061279
index :  4
[15] (1,)
[15]
[182  95 442 370]
Crop Image:  (275,

prediction:  [[1.3296918e-02 1.5277941e-04 5.1449813e-02 4.5788655e-01 3.6260846e-01
  8.3897226e-03 1.0621578e-01]]
Max:  0.013296918012201786
Max:  0.051449812948703766
Max:  0.45788654685020447
index :  3
[15] (1,)
[15]
[200 106 426 360]
Crop Image:  (254, 226, 3)
(48, 48)
prediction:  [[0.01775699 0.00233754 0.13279854 0.38031363 0.2706592  0.03591474
  0.16021942]]
Max:  0.0177569929510355
Max:  0.13279853761196136
Max:  0.3803136348724365
index :  3
[15] (1,)
[15]
[202 107 423 359]
Crop Image:  (252, 221, 3)
(48, 48)
prediction:  [[0.02316457 0.00165908 0.06559096 0.45225447 0.22830473 0.02062969
  0.20839646]]
Max:  0.023164570331573486
Max:  0.06559096276760101
Max:  0.4522544741630554
index :  3
[15] (1,)
[15]
[200 110 426 356]
Crop Image:  (246, 226, 3)
(48, 48)
prediction:  [[1.5822852e-02 1.5851996e-04 5.3662509e-02 3.0406776e-01 5.5162609e-01
  1.2547242e-02 6.2114984e-02]]
Max:  0.01582285203039646
Max:  0.053662508726119995
Max:  0.3040677607059479
Max:  0.55162608623504

[15] (1,)
[15]
[201 130 431 341]
Crop Image:  (211, 230, 3)
(48, 48)
prediction:  [[0.21269514 0.00051879 0.0698601  0.25522837 0.41337585 0.00375704
  0.04456472]]
Max:  0.2126951366662979
Max:  0.2552283704280853
Max:  0.4133758544921875
index :  4
[15 15] (2,)
[15 15]
[203 129 431 341]
Crop Image:  (212, 228, 3)
(48, 48)
prediction:  [[0.24188311 0.00220166 0.06332035 0.15185547 0.48511815 0.00506592
  0.05055533]]
Max:  0.24188311398029327
Max:  0.48511815071105957
index :  4
[  1 295 113 185]
Crop Image:  (0, 112, 3)
[15] (1,)
[15]
[201 126 434 346]
Crop Image:  (220, 233, 3)
(48, 48)
prediction:  [[0.2931175  0.00084551 0.01909486 0.35262567 0.29979813 0.00172918
  0.03278912]]
Max:  0.293117493391037
Max:  0.35262566804885864
index :  3
[15] (1,)
[15]
[201 128 433 343]
Crop Image:  (215, 232, 3)
(48, 48)
prediction:  [[0.17999604 0.00123331 0.04467844 0.38799518 0.3342779  0.00296347
  0.04885562]]
Max:  0.1799960434436798
Max:  0.387995183467865
index :  3
[15] (1,)
[15]
[203 1

prediction:  [[0.2622385  0.00713063 0.04512065 0.11016209 0.32158718 0.04267743
  0.21108356]]
Max:  0.2622385025024414
Max:  0.3215871751308441
index :  4
[15] (1,)
[15]
[214 131 420 340]
Crop Image:  (209, 206, 3)
(48, 48)
prediction:  [[3.2712838e-01 1.1104611e-04 3.2822117e-02 5.0690256e-02 3.6218014e-01
  3.8481705e-02 1.8858637e-01]]
Max:  0.3271283805370331
Max:  0.3621801435947418
index :  4
[15] (1,)
[15]
[209 131 424 340]
Crop Image:  (209, 215, 3)
(48, 48)
prediction:  [[0.25911427 0.0016079  0.04459447 0.1783032  0.28872597 0.01788287
  0.20977132]]
Max:  0.25911426544189453
Max:  0.28872597217559814
index :  4
[15] (1,)
[15]
[213 129 420 342]
Crop Image:  (213, 207, 3)
(48, 48)
prediction:  [[0.519747   0.00253998 0.05518042 0.03544734 0.23630686 0.037436
  0.11334244]]
Max:  0.5197470188140869
index :  0
[15] (1,)
[15]
[206 128 428 344]
Crop Image:  (216, 222, 3)
(48, 48)
prediction:  [[0.17157322 0.01728947 0.02575561 0.04178875 0.45628947 0.02490275
  0.2624007 ]]
Max:

prediction:  [[2.1609256e-02 2.3306588e-05 1.3952456e-01 5.3381586e-01 6.6251099e-02
  1.8792312e-01 5.0852757e-02]]
Max:  0.02160925604403019
Max:  0.13952456414699554
Max:  0.533815860748291
index :  3
[15] (1,)
[15]
[ 28  39 591 429]
Crop Image:  (390, 563, 3)
(48, 48)
prediction:  [[1.6758172e-02 3.2416989e-05 1.4696333e-01 5.6821477e-01 1.3249898e-01
  7.9589114e-02 5.5943299e-02]]
Max:  0.01675817184150219
Max:  0.14696332812309265
Max:  0.5682147741317749
index :  3
[15] (1,)
[15]
[ 31  44 588 423]
Crop Image:  (379, 557, 3)
(48, 48)
prediction:  [[1.06089935e-02 4.16782714e-05 1.42373547e-01 6.31770074e-01
  9.83083248e-02 4.02221195e-02 7.66751617e-02]]
Max:  0.010608993470668793
Max:  0.14237354695796967
Max:  0.6317700743675232
index :  3
[15] (1,)
[15]
[ 24  54 595 413]
Crop Image:  (359, 571, 3)
(48, 48)
prediction:  [[1.5419583e-02 1.8215284e-04 1.7142063e-01 2.5020176e-01 4.3855783e-01
  5.1690709e-02 7.2527200e-02]]
Max:  0.015419582836329937
Max:  0.1714206337928772
Ma

Max:  0.3025667667388916
index :  4
[15] (1,)
[15]
[ 35  66 585 401]
Crop Image:  (335, 550, 3)
(48, 48)
prediction:  [[4.3701999e-02 9.8547003e-05 4.0038207e-01 3.2149759e-01 1.4601295e-01
  4.3439079e-02 4.4867784e-02]]
Max:  0.04370199888944626
Max:  0.40038207173347473
index :  2
[15] (1,)
[15]
[ 27  66 593 401]
Crop Image:  (335, 566, 3)
(48, 48)
prediction:  [[1.0200229e-01 7.4469019e-05 2.4598402e-01 2.9898906e-01 2.4582122e-01
  4.9223240e-02 5.7905748e-02]]
Max:  0.10200229287147522
Max:  0.2459840178489685
Max:  0.29898905754089355
index :  3
[15] (1,)
[15]
[ 24  69 596 398]
Crop Image:  (329, 572, 3)
(48, 48)
prediction:  [[5.0870080e-02 5.4588974e-05 2.7085170e-01 2.5185433e-01 3.5619324e-01
  1.5340030e-02 5.4836016e-02]]
Max:  0.050870079547166824
Max:  0.2708517014980316
Max:  0.3561932444572449
index :  4
[15] (1,)
[15]
[ 26  66 594 401]
Crop Image:  (335, 568, 3)
(48, 48)
prediction:  [[7.9534449e-02 1.9003074e-04 3.2319281e-01 2.3768094e-01 2.7469429e-01
  3.4406278e-

[15] (1,)
[15]
[ 32  72 587 395]
Crop Image:  (323, 555, 3)
(48, 48)
prediction:  [[1.7203808e-01 1.3693958e-04 2.9458255e-01 1.3492283e-01 2.8774291e-01
  2.5827985e-02 8.4748819e-02]]
Max:  0.17203807830810547
Max:  0.2945825457572937
index :  2
[15] (1,)
[15]
[ 32  70 586 397]
Crop Image:  (327, 554, 3)
(48, 48)
prediction:  [[2.7026975e-01 6.5786779e-05 2.1870461e-01 1.7928056e-01 2.4922451e-01
  2.6687203e-02 5.5767577e-02]]
Max:  0.2702697515487671
index :  0
[15] (1,)
[15]
[ 32  70 587 397]
Crop Image:  (327, 555, 3)
(48, 48)
prediction:  [[2.4089128e-01 6.0230941e-05 1.9875734e-01 2.0943558e-01 2.3619720e-01
  3.9938655e-02 7.4719690e-02]]
Max:  0.24089127779006958
index :  0
[15] (1,)
[15]
[ 33  70 586 397]
Crop Image:  (327, 553, 3)
(48, 48)
prediction:  [[2.6606381e-01 6.2894200e-05 1.4265859e-01 2.2547044e-01 2.3353198e-01
  3.7589982e-02 9.4622329e-02]]
Max:  0.2660638093948364
index :  0
[15] (1,)
[15]
[ 31  65 588 402]
Crop Image:  (337, 557, 3)
(48, 48)
prediction:  [[3

prediction:  [[2.6933458e-01 4.0647716e-05 1.5249828e-01 2.4416779e-01 2.5530982e-01
  1.3640103e-02 6.5008700e-02]]
Max:  0.2693345844745636
index :  0
[15] (1,)
[15]
[ 27  70 592 396]
Crop Image:  (326, 565, 3)
(48, 48)
prediction:  [[2.8449836e-01 4.1171428e-05 1.4573590e-01 2.1593288e-01 2.9589301e-01
  6.7795594e-03 5.1119145e-02]]
Max:  0.2844983637332916
Max:  0.29589301347732544
index :  4
[15] (1,)
[15]
[ 32  73 587 393]
Crop Image:  (320, 555, 3)
(48, 48)
prediction:  [[3.9463547e-01 2.1111791e-05 1.3789904e-01 1.6805899e-01 2.0240754e-01
  1.6621271e-02 8.0356598e-02]]
Max:  0.39463546872138977
index :  0
[15] (1,)
[15]
[ 33  69 585 398]
Crop Image:  (329, 552, 3)
(48, 48)
prediction:  [[2.7254930e-01 6.8950503e-05 1.1741994e-01 2.0491232e-01 2.7426594e-01
  2.3889538e-02 1.0689398e-01]]
Max:  0.2725493013858795
Max:  0.27426594495773315
index :  4
[15] (1,)
[15]
[ 36  72 581 395]
Crop Image:  (323, 545, 3)
(48, 48)
prediction:  [[2.3836678e-01 1.1085856e-04 2.0266853e-01 2.

[15] (1,)
[15]
[ 34 104 583 364]
Crop Image:  (260, 549, 3)
(48, 48)
prediction:  [[0.47627345 0.00068496 0.13063894 0.23256052 0.14697853 0.0050387
  0.00782498]]
Max:  0.47627344727516174
index :  0
[15] (1,)
[15]
[ 34 102 583 366]
Crop Image:  (264, 549, 3)
(48, 48)
prediction:  [[5.04208624e-01 4.18164476e-04 1.65316105e-01 2.06330359e-01
  1.12371385e-01 4.63461317e-03 6.72066258e-03]]
Max:  0.5042086243629456
index :  0
[15] (1,)
[15]
[ 41 102 576 366]
Crop Image:  (264, 535, 3)
(48, 48)
prediction:  [[0.75452185 0.00586918 0.0621569  0.06253878 0.10554879 0.00184299
  0.00752159]]
Max:  0.7545218467712402
index :  0
[15] (1,)
[15]
[ 38  99 579 368]
Crop Image:  (269, 541, 3)
(48, 48)
prediction:  [[0.66647196 0.00161861 0.11390546 0.07343945 0.12826748 0.00426198
  0.01203507]]
Max:  0.6664719581604004
index :  0
[15] (1,)
[15]
[ 36 101 580 367]
Crop Image:  (266, 544, 3)
(48, 48)
prediction:  [[0.54330426 0.00106031 0.17609861 0.16168867 0.09979741 0.00708185
  0.01096889]]
Max

[15 15] (2,)
[15 15]
[ 38 103 579 365]
Crop Image:  (262, 541, 3)
(48, 48)
prediction:  [[0.80391747 0.00588815 0.06052298 0.06370637 0.05301414 0.00989533
  0.00305559]]
Max:  0.8039174675941467
index :  0
[  4 295 107 185]
Crop Image:  (0, 103, 3)
[15] (1,)
[15]
[ 42 104 575 364]
Crop Image:  (260, 533, 3)
(48, 48)
prediction:  [[0.79347116 0.02419124 0.04101457 0.0797943  0.05490293 0.00294178
  0.00368392]]
Max:  0.7934711575508118
index :  0
[15] (1,)
[15]
[ 43 106 572 361]
Crop Image:  (255, 529, 3)
(48, 48)
prediction:  [[0.62571967 0.00996805 0.09029028 0.12963957 0.1274891  0.0067273
  0.01016612]]
Max:  0.6257196664810181
index :  0
[15] (1,)
[15]
[ 32 106 585 361]
Crop Image:  (255, 553, 3)
(48, 48)
prediction:  [[0.38212082 0.00042717 0.2397232  0.14702995 0.2119873  0.0053539
  0.01335774]]
Max:  0.382120817899704
index :  0
[15] (1,)
[15]
[ 35  98 588 371]
Crop Image:  (273, 553, 3)
(48, 48)
prediction:  [[7.7304494e-01 5.0904852e-04 7.7651322e-02 5.6365509e-02 6.5588169e

[15] (1,)
[15]
[ 30 107 588 360]
Crop Image:  (253, 558, 3)
(48, 48)
prediction:  [[4.8185058e-02 1.8232239e-04 2.3012549e-01 4.3847397e-01 2.1958487e-01
  1.9505162e-02 4.3943126e-02]]
Max:  0.04818505793809891
Max:  0.23012548685073853
Max:  0.43847396969795227
index :  3
[15] (1,)
[15]
[ 32 107 587 360]
Crop Image:  (253, 555, 3)
(48, 48)
prediction:  [[0.06200317 0.00059602 0.11894733 0.56123513 0.16909085 0.02656061
  0.06156686]]
Max:  0.06200316548347473
Max:  0.11894732713699341
Max:  0.5612351298332214
index :  3
[15] (1,)
[15]
[ 35 102 582 365]
Crop Image:  (263, 547, 3)
(48, 48)
prediction:  [[0.55522925 0.0107161  0.1685911  0.13903712 0.1119858  0.00922044
  0.00522007]]
Max:  0.5552292466163635
index :  0
[15] (1,)
[15]
[ 36  98 583 369]
Crop Image:  (271, 547, 3)
(48, 48)
prediction:  [[0.7364641  0.00423501 0.10102325 0.07791613 0.06762377 0.00989555
  0.00284216]]
Max:  0.7364640831947327
index :  0
[15] (1,)
[15]
[ 36 103 582 364]
Crop Image:  (261, 546, 3)
(48, 48)
p

[15] (1,)
[15]
[ 42 101 576 367]
Crop Image:  (266, 534, 3)
(48, 48)
prediction:  [[0.6437784  0.00229224 0.12379548 0.08283536 0.11506896 0.01261527
  0.01961436]]
Max:  0.643778383731842
index :  0
[15] (1,)
[15]
[ 39  96 580 372]
Crop Image:  (276, 541, 3)
(48, 48)
prediction:  [[3.4720400e-01 1.2309931e-04 1.6934848e-01 3.4122476e-01 9.7529024e-02
  2.1637755e-02 2.2932855e-02]]
Max:  0.3472039997577667
index :  0
[15] (1,)
[15]
[ 38 100 580 368]
Crop Image:  (268, 542, 3)
(48, 48)
prediction:  [[0.4593441  0.00126486 0.13227005 0.24138403 0.12231395 0.01883281
  0.02459013]]
Max:  0.4593440890312195
index :  0
[15] (1,)
[15]
[ 33  97 586 370]
Crop Image:  (273, 553, 3)
(48, 48)
prediction:  [[1.8108974e-01 7.8552039e-05 1.1833160e-01 4.5684749e-01 1.6429029e-01
  1.5574494e-02 6.3787818e-02]]
Max:  0.18108974397182465
Max:  0.45684748888015747
index :  3
[15] (1,)
[15]
[ 48  99 572 369]
Crop Image:  (270, 524, 3)
(48, 48)
prediction:  [[6.79677486e-01 6.21005660e-04 1.08081616e-01

[15] (1,)
[15]
[ 35 103 583 365]
Crop Image:  (262, 548, 3)
(48, 48)
prediction:  [[0.34786084 0.01017361 0.07117883 0.4018549  0.14147496 0.00478837
  0.02266839]]
Max:  0.34786084294319153
Max:  0.40185490250587463
index :  3
[15] (1,)
[15]
[ 35 103 583 365]
Crop Image:  (262, 548, 3)
(48, 48)
prediction:  [[0.32514665 0.00364832 0.09651013 0.4055778  0.14448236 0.00364303
  0.02099163]]
Max:  0.3251466453075409
Max:  0.40557780861854553
index :  3
[15] (1,)
[15]
[ 33 102 585 365]
Crop Image:  (263, 552, 3)
(48, 48)
prediction:  [[0.2980166  0.0006951  0.13842581 0.32004943 0.20620424 0.00738288
  0.02922584]]
Max:  0.29801660776138306
Max:  0.3200494349002838
index :  3
[15] (1,)
[15]
[ 38 105 579 363]
Crop Image:  (258, 541, 3)
(48, 48)
prediction:  [[0.42141327 0.0185862  0.0712119  0.32816467 0.12426624 0.00697314
  0.02938457]]
Max:  0.42141327261924744
index :  0
[9] (1,)
chair
[]
[9] (1,)
chair
[]
[9] (1,)
chair
[]
[9] (1,)
chair
[]
[9] (1,)
chair
[]
[15] (1,)
[15]
[ 30  98 58

[15] (1,)
[15]
[ 36 108 579 359]
Crop Image:  (251, 543, 3)
(48, 48)
prediction:  [[0.44988665 0.01661422 0.13731112 0.22871043 0.14442906 0.00118403
  0.02186433]]
Max:  0.44988664984703064
index :  0
[15] (1,)
[15]
[ 49 105 569 363]
Crop Image:  (258, 520, 3)
(48, 48)
prediction:  [[0.8349211  0.07762925 0.02506221 0.03416445 0.02401232 0.00216426
  0.00204626]]
Max:  0.83492112159729
index :  0
[15] (1,)
[15]
[ 47 106 571 362]
Crop Image:  (256, 524, 3)
(48, 48)
prediction:  [[0.6403249  0.15331711 0.04327957 0.10156646 0.04456394 0.00675297
  0.01019512]]
Max:  0.6403248906135559
index :  0
[15] (1,)
[15]
[ 45 101 573 366]
Crop Image:  (265, 528, 3)
(48, 48)
prediction:  [[0.7579881  0.00221396 0.08339201 0.04569387 0.07758075 0.02213863
  0.0109927 ]]
Max:  0.7579880952835083
index :  0
[15] (1,)
[15]
[ 26  79 592 388]
Crop Image:  (309, 566, 3)
(48, 48)
prediction:  [[0.08116662 0.00069738 0.4673806  0.2013755  0.13607314 0.09172062
  0.02158606]]
Max:  0.08116661757230759
Max:  

prediction:  [[0.194749   0.00304237 0.09318914 0.19484825 0.422818   0.00559368
  0.08575951]]
Max:  0.19474899768829346
Max:  0.19484825432300568
Max:  0.42281800508499146
index :  4
[15] (1,)
[15]
[ 40  96 579 371]
Crop Image:  (275, 539, 3)
(48, 48)
prediction:  [[0.25030172 0.0012976  0.13663419 0.11944384 0.4329547  0.00404444
  0.05532344]]
Max:  0.250301718711853
Max:  0.43295469880104065
index :  4
[15] (1,)
[15]
[ 44  99 575 368]
Crop Image:  (269, 531, 3)
(48, 48)
prediction:  [[4.1920653e-01 1.7598788e-04 1.9076192e-01 7.9215333e-02 2.4911289e-01
  8.6076176e-03 5.2919589e-02]]
Max:  0.41920652985572815
index :  0
[15] (1,)
[15]
[ 42  96 577 372]
Crop Image:  (276, 535, 3)
(48, 48)
prediction:  [[0.19706325 0.00144141 0.12908709 0.13738175 0.4736197  0.00516151
  0.05624529]]
Max:  0.19706325232982635
Max:  0.4736196994781494
index :  4
[15 15] (2,)
[15 15]
[ 42  99 577 369]
Crop Image:  (270, 535, 3)
(48, 48)
prediction:  [[5.8940494e-01 3.6506401e-04 1.4638737e-01 5.77671

[15 15] (2,)
[15 15]
[ 48  99 569 369]
Crop Image:  (270, 521, 3)
(48, 48)
prediction:  [[0.41391566 0.00216711 0.07195572 0.35796785 0.12887494 0.0035468
  0.02157182]]
Max:  0.4139156639575958
index :  0
[  5 298 106 182]
Crop Image:  (0, 101, 3)
[15] (1,)
[15]
[ 49  98 569 370]
Crop Image:  (272, 520, 3)
(48, 48)
prediction:  [[0.38526353 0.00359511 0.06429975 0.37515163 0.15042193 0.00272948
  0.01853865]]
Max:  0.3852635324001312
index :  0
[15 15] (2,)
[15 15]
[ 58 103 560 365]
Crop Image:  (262, 502, 3)
(48, 48)
prediction:  [[4.5152304e-01 4.1106675e-04 1.1137991e-01 3.4121129e-01 7.7374250e-02
  1.4415586e-03 1.6658906e-02]]
Max:  0.4515230357646942
index :  0
[  5 297 104 183]
Crop Image:  (0, 99, 3)
[15 15] (2,)
[15 15]
[ 44  96 574 371]
Crop Image:  (275, 530, 3)
(48, 48)
prediction:  [[0.50385344 0.01350362 0.05367619 0.1754688  0.2301852  0.00110417
  0.02220857]]
Max:  0.503853440284729
index :  0
[  2 293 107 187]
Crop Image:  (0, 105, 3)
[15] (1,)
[15]
[ 45  99 573 368

[15] (1,)
[15]
[ 41  91 571 375]
Crop Image:  (284, 530, 3)
(48, 48)
prediction:  [[0.27252167 0.0089758  0.1050665  0.18808866 0.36116308 0.01267522
  0.05150904]]
Max:  0.2725216746330261
Max:  0.36116307973861694
index :  4
[15] (1,)
[15]
[ 52  93 555 374]
Crop Image:  (281, 503, 3)
(48, 48)
prediction:  [[0.41824126 0.03229324 0.0343581  0.1655074  0.25720716 0.0062041
  0.08618885]]
Max:  0.4182412624359131
index :  0
[15] (1,)
[15]
[ 43  94 565 367]
Crop Image:  (273, 522, 3)
(48, 48)
prediction:  [[0.64810807 0.00547828 0.07523028 0.11835247 0.12505431 0.00408607
  0.02369049]]
Max:  0.6481080651283264
index :  0
[15 15] (2,)
[15 15]
[ 44  91 568 373]
Crop Image:  (282, 524, 3)
(48, 48)
prediction:  [[0.42863595 0.00820678 0.08803795 0.19720787 0.22662507 0.00699676
  0.04428961]]
Max:  0.42863595485687256
index :  0
[  4 297 104 183]
Crop Image:  (0, 100, 3)
[15] (1,)
[15]
[ 39  95 577 374]
Crop Image:  (279, 538, 3)
(48, 48)
prediction:  [[0.20019259 0.00135563 0.12878482 0.25

[15 15] (2,)
[15 15]
[ 45  96 572 371]
Crop Image:  (275, 527, 3)
(48, 48)
prediction:  [[0.40231574 0.01183329 0.04757859 0.342087   0.17189556 0.00651408
  0.01777576]]
Max:  0.40231573581695557
index :  0
[  4 295 107 185]
Crop Image:  (0, 103, 3)
[15] (1,)
[15]
[ 36  94 582 373]
Crop Image:  (279, 546, 3)
(48, 48)
prediction:  [[0.32457995 0.00692662 0.09249185 0.19978477 0.32585862 0.00576121
  0.04459691]]
Max:  0.32457995414733887
Max:  0.32585862278938293
index :  4
[15] (1,)
[15]
[ 40  98 575 369]
Crop Image:  (271, 535, 3)
(48, 48)
prediction:  [[0.50887394 0.0014651  0.04458417 0.24925546 0.1384778  0.01451887
  0.04282457]]
Max:  0.5088739395141602
index :  0
[15] (1,)
[15]
[ 40  93 576 374]
Crop Image:  (281, 536, 3)
(48, 48)
prediction:  [[0.31373122 0.00128216 0.09333149 0.2763276  0.26469123 0.00937907
  0.04125721]]
Max:  0.31373122334480286
index :  0
[15] (1,)
[15]
[ 39  91 579 377]
Crop Image:  (286, 540, 3)
(48, 48)
prediction:  [[0.20945455 0.00094706 0.24216634 0

prediction:  [[0.86298656 0.00102564 0.01672969 0.08122051 0.03315332 0.00090388
  0.00398042]]
Max:  0.8629865646362305
index :  0
[15] (1,)
[15]
[ 45 101 573 366]
Crop Image:  (265, 528, 3)
(48, 48)
prediction:  [[0.59636897 0.00252053 0.03883423 0.19420378 0.15534012 0.00277405
  0.00995837]]
Max:  0.5963689684867859
index :  0
[15] (1,)
[15]
[ 53  98 567 369]
Crop Image:  (271, 514, 3)
(48, 48)
prediction:  [[0.2820254  0.00092453 0.08443327 0.46817708 0.14946713 0.00700155
  0.00797097]]
Max:  0.28202539682388306
Max:  0.46817708015441895
index :  3
[15 15] (2,)
[15 15]
[ 58  99 561 368]
Crop Image:  (269, 503, 3)
(48, 48)
prediction:  [[0.47394603 0.00081393 0.08079294 0.2907008  0.13441853 0.0074586
  0.01186919]]
Max:  0.4739460349082947
index :  0
[  3 297 108 183]
Crop Image:  (0, 105, 3)
[15] (1,)
[15]
[ 52  99 566 368]
Crop Image:  (269, 514, 3)
(48, 48)
prediction:  [[1.9784881e-01 1.1668552e-04 7.1790218e-02 6.1920655e-01 1.0023881e-01
  4.7007254e-03 6.0982117e-03]]
Max:

prediction:  [[0.13145874 0.00098454 0.04797013 0.31118143 0.47847268 0.00125902
  0.02867347]]
Max:  0.13145874440670013
Max:  0.3111814260482788
Max:  0.47847267985343933
index :  4
[15] (1,)
[15]
[ 52  91 567 375]
Crop Image:  (284, 515, 3)
(48, 48)
prediction:  [[0.31691563 0.00310171 0.04814859 0.2523336  0.35743508 0.00189275
  0.02017274]]
Max:  0.3169156312942505
Max:  0.35743507742881775
index :  4
[15 15] (2,)
[15 15]
[ 47  85 572 381]
Crop Image:  (296, 525, 3)
(48, 48)
prediction:  [[0.62208647 0.00124801 0.04007724 0.19290192 0.12354838 0.00485293
  0.01528494]]
Max:  0.6220864653587341
index :  0
[  2 297 107 183]
Crop Image:  (0, 105, 3)
[15] (1,)
[15]
[ 40  93 578 373]
Crop Image:  (280, 538, 3)
(48, 48)
prediction:  [[0.52683014 0.0015414  0.05198124 0.30036026 0.11001468 0.00156161
  0.00771077]]
Max:  0.5268301367759705
index :  0
[15] (1,)
[15]
[ 53  90 567 376]
Crop Image:  (286, 514, 3)
(48, 48)
prediction:  [[0.23966254 0.00057831 0.03141099 0.5770312  0.13806671

prediction:  [[0.28172588 0.00271805 0.0534585  0.17986742 0.46598786 0.00573721
  0.01050505]]
Max:  0.2817258834838867
Max:  0.4659878611564636
index :  4
[15] (1,)
[15]
[ 41  92 577 374]
Crop Image:  (282, 536, 3)
(48, 48)
prediction:  [[0.25527093 0.00071292 0.09316142 0.3728595  0.2577376  0.01134087
  0.00891665]]
Max:  0.25527092814445496
Max:  0.37285950779914856
index :  3
[15] (1,)
[15]
[ 46  88 574 378]
Crop Image:  (290, 528, 3)
(48, 48)
prediction:  [[4.6825436e-01 1.4101043e-04 4.4480469e-02 1.5808582e-01 3.1051001e-01
  6.7045111e-03 1.1823814e-02]]
Max:  0.46825435757637024
index :  0
[15] (1,)
[15]
[ 44  89 575 377]
Crop Image:  (288, 531, 3)
(48, 48)
prediction:  [[2.8996953e-01 9.5516094e-05 1.1079475e-01 2.4863900e-01 3.3034676e-01
  5.4421332e-03 1.4712307e-02]]
Max:  0.2899695336818695
Max:  0.3303467631340027
index :  4
[15] (1,)
[15]
[ 50  94 569 372]
Crop Image:  (278, 519, 3)
(48, 48)
prediction:  [[0.6493779  0.00201903 0.04654403 0.09149581 0.20241453 0.0011

[15] (1,)
[15]
[ 51  98 567 368]
Crop Image:  (270, 516, 3)
(48, 48)
prediction:  [[4.2339242e-01 1.4826731e-04 1.6196072e-01 1.8985507e-01 2.1117848e-01
  2.5300269e-03 1.0934877e-02]]
Max:  0.4233924150466919
index :  0
[15] (1,)
[15]
[ 49  98 570 368]
Crop Image:  (270, 521, 3)
(48, 48)
prediction:  [[3.6568770e-01 2.5711447e-04 1.6083819e-01 1.9426727e-01 2.6235238e-01
  2.8193698e-03 1.3778020e-02]]
Max:  0.36568769812583923
index :  0
[15] (1,)
[15]
[ 51  97 568 369]
Crop Image:  (272, 517, 3)
(48, 48)
prediction:  [[3.2609719e-01 1.8523424e-04 1.3806359e-01 2.5067267e-01 2.6766488e-01
  4.1552950e-03 1.3161176e-02]]
Max:  0.32609719038009644
index :  0
[15] (1,)
[15]
[ 51 100 567 367]
Crop Image:  (267, 516, 3)
(48, 48)
prediction:  [[0.36671993 0.00052457 0.12499011 0.26396635 0.22313389 0.00317524
  0.01748998]]
Max:  0.36671993136405945
index :  0
[15] (1,)
[15]
[ 58  95 561 372]
Crop Image:  (277, 503, 3)
(48, 48)
prediction:  [[5.35191894e-01 1.00332676e-04 1.37952030e-01 1

prediction:  [[4.7499111e-01 1.4461088e-04 1.1859092e-01 1.2769353e-01 2.5627941e-01
  1.9333245e-03 2.0367134e-02]]
Max:  0.474991112947464
index :  0
[15] (1,)
[15]
[ 56 102 562 366]
Crop Image:  (264, 506, 3)
(48, 48)
prediction:  [[4.68904048e-01 2.43911025e-04 1.11914791e-01 2.73704201e-01
  1.27687722e-01 3.52574978e-03 1.40194865e-02]]
Max:  0.468904048204422
index :  0
[15] (1,)
[15]
[ 52 103 567 364]
Crop Image:  (261, 515, 3)
(48, 48)
prediction:  [[3.0069754e-01 3.3331879e-05 1.8728237e-01 3.4227630e-01 1.3687402e-01
  5.9056063e-03 2.6930854e-02]]
Max:  0.30069753527641296
Max:  0.34227630496025085
index :  3
[15] (1,)
[15]
[ 58 102 561 365]
Crop Image:  (263, 503, 3)
(48, 48)
prediction:  [[5.0243443e-01 7.9904712e-05 1.3896608e-01 2.5759119e-01 8.6140357e-02
  2.2493466e-03 1.2538641e-02]]
Max:  0.5024344325065613
index :  0
[15] (1,)
[15]
[ 54 102 564 365]
Crop Image:  (263, 510, 3)
(48, 48)
prediction:  [[5.20477593e-01 6.30602444e-05 1.02869324e-01 1.60573184e-01
  1.9

prediction:  [[0.6073084  0.00157832 0.09314252 0.20278992 0.07727004 0.01210536
  0.00580541]]
Max:  0.6073083877563477
index :  0
[  6 298 104 182]
Crop Image:  (0, 98, 3)
[15] (1,)
[15]
[ 47  96 571 371]
Crop Image:  (275, 524, 3)
(48, 48)
prediction:  [[0.4495677  0.06227208 0.11765742 0.17611806 0.16931131 0.01339358
  0.01167989]]
Max:  0.4495677053928375
index :  0
[15] (1,)
[15]
[ 50  95 569 372]
Crop Image:  (277, 519, 3)
(48, 48)
prediction:  [[0.35065305 0.06337232 0.05367311 0.24029237 0.25380242 0.01959172
  0.01861505]]
Max:  0.3506530523300171
index :  0
[15] (1,)
[15]
[ 35  96 583 370]
Crop Image:  (274, 548, 3)
(48, 48)
prediction:  [[0.6581186  0.00411983 0.04816945 0.1677415  0.10747635 0.00749546
  0.00687884]]
Max:  0.6581186056137085
index :  0
[15] (1,)
[15]
[ 42  92 577 374]
Crop Image:  (282, 535, 3)
(48, 48)
prediction:  [[0.46988162 0.01657836 0.05287976 0.25144488 0.1895401  0.00840183
  0.01127338]]
Max:  0.4698816239833832
index :  0
[15] (1,)
[15]
[ 59  9

[15] (1,)
[15]
[140  94 480 376]
Crop Image:  (282, 340, 3)
(48, 48)
prediction:  [[2.0219803e-01 9.7182601e-06 2.0149311e-01 9.1591567e-02 2.9823279e-01
  1.2621260e-01 8.0262199e-02]]
Max:  0.20219802856445312
Max:  0.2982327938079834
index :  4
[15] (1,)
[15]
[130  94 487 372]
Crop Image:  (278, 357, 3)
(48, 48)
prediction:  [[6.1327624e-03 2.8384955e-05 1.2231485e-02 6.6737108e-02 7.8313166e-01
  3.7718012e-03 1.2796685e-01]]
Max:  0.006132762413471937
Max:  0.012231484986841679
Max:  0.0667371079325676
Max:  0.7831316590309143
index :  4
[15] (1,)
[15]
[152  89 469 376]
Crop Image:  (287, 317, 3)
(48, 48)
prediction:  [[5.9860993e-02 7.1987859e-05 8.1248567e-02 1.6381361e-01 5.8241874e-01
  2.6971351e-02 8.5614793e-02]]
Max:  0.059860993176698685
Max:  0.08124856650829315
Max:  0.16381360590457916
Max:  0.5824187397956848
index :  4
[15] (1,)
[15]
[110  96 511 371]
Crop Image:  (275, 401, 3)
(48, 48)
prediction:  [[0.01998854 0.00144479 0.05145049 0.07955994 0.7645385  0.00279768


prediction:  [[0.20234129 0.00335862 0.21783991 0.16245462 0.21828862 0.15594463
  0.03977223]]
Max:  0.20234128832817078
Max:  0.21783991158008575
Max:  0.2182886153459549
index :  4
[15] (1,)
[15]
[ 29  95 589 371]
Crop Image:  (276, 560, 3)
(48, 48)
prediction:  [[0.2373764  0.00904525 0.24460888 0.33338475 0.10932359 0.03076934
  0.03549178]]
Max:  0.237376406788826
Max:  0.24460887908935547
Max:  0.33338475227355957
index :  3
[15] (1,)
[15]
[ 29  95 589 371]
Crop Image:  (276, 560, 3)
(48, 48)
prediction:  [[1.3279741e-01 7.7844343e-05 3.3808452e-01 3.4341282e-01 1.0760562e-01
  1.4999304e-02 6.3022576e-02]]
Max:  0.13279740512371063
Max:  0.33808451890945435
Max:  0.3434128165245056
index :  3
[15] (1,)
[15]
[ 29  85 589 380]
Crop Image:  (295, 560, 3)
(48, 48)
prediction:  [[0.11068852 0.00053072 0.49382854 0.06525161 0.15472697 0.05151935
  0.12345427]]
Max:  0.11068851500749588
Max:  0.49382853507995605
index :  2
[15] (1,)
[15]
[ 21  84 597 381]
Crop Image:  (297, 576, 3)
(4

prediction:  [[0.11093003 0.00095275 0.24268684 0.08788733 0.38573152 0.02506258
  0.146749  ]]
Max:  0.11093003302812576
Max:  0.24268683791160583
Max:  0.3857315182685852
index :  4
[15] (1,)
[15]
[ 23  95 595 371]
Crop Image:  (276, 572, 3)
(48, 48)
prediction:  [[0.15355651 0.00065776 0.30220363 0.12586875 0.3302427  0.00253612
  0.08493453]]
Max:  0.15355651080608368
Max:  0.30220362544059753
Max:  0.33024269342422485
index :  4
[15] (1,)
[15]
[ 23  96 594 369]
Crop Image:  (273, 571, 3)
(48, 48)
prediction:  [[0.24385683 0.0027151  0.16642335 0.06823131 0.38925776 0.00279325
  0.12672241]]
Max:  0.24385683238506317
Max:  0.3892577588558197
index :  4
[15] (1,)
[15]
[ 23  92 594 373]
Crop Image:  (281, 571, 3)
(48, 48)
prediction:  [[0.07146005 0.00051754 0.32657316 0.11801124 0.35977793 0.00424448
  0.11941566]]
Max:  0.0714600458741188
Max:  0.3265731632709503
Max:  0.35977792739868164
index :  4
[15] (1,)
[15]
[ 23  92 594 373]
Crop Image:  (281, 571, 3)
(48, 48)
prediction:  [

prediction:  [[0.43705714 0.00225085 0.06020188 0.0676259  0.279286   0.00812072
  0.14545761]]
Max:  0.43705713748931885
index :  0
[15] (1,)
[15]
[ 26  88 592 377]
Crop Image:  (289, 566, 3)
(48, 48)
prediction:  [[0.49934033 0.00178764 0.02225075 0.03314142 0.3280201  0.00326426
  0.11219548]]
Max:  0.49934032559394836
index :  0
[15] (1,)
[15]
[ 22  87 596 378]
Crop Image:  (291, 574, 3)
(48, 48)
prediction:  [[0.5169745  0.01174533 0.05712622 0.07644081 0.20843071 0.0073162
  0.12196626]]
Max:  0.5169745087623596
index :  0
[15] (1,)
[15]
[ 23  89 595 376]
Crop Image:  (287, 572, 3)
(48, 48)
prediction:  [[0.48491833 0.00244362 0.05304844 0.05588759 0.26739347 0.01096008
  0.12534846]]
Max:  0.4849183261394501
index :  0
[15] (1,)
[15]
[ 29  88 589 377]
Crop Image:  (289, 560, 3)
(48, 48)
prediction:  [[0.2838178  0.00157976 0.19430833 0.04290149 0.36703253 0.00591736
  0.10444274]]
Max:  0.2838177978992462
Max:  0.367032527923584
index :  4
[15] (1,)
[15]
[ 22  88 596 377]
Crop I

prediction:  [[0.16649772 0.0005131  0.08353054 0.0368697  0.2973625  0.00458225
  0.41064417]]
Max:  0.16649772226810455
Max:  0.2973625063896179
Max:  0.41064417362213135
index :  6
[15] (1,)
[15]
[ 27  95 590 370]
Crop Image:  (275, 563, 3)
(48, 48)
prediction:  [[3.8092995e-01 3.1966981e-04 5.7645861e-02 4.7039062e-02 2.8039810e-01
  3.6615736e-03 2.3000582e-01]]
Max:  0.38092994689941406
index :  0
[15] (1,)
[15]
[ 26  93 591 372]
Crop Image:  (279, 565, 3)
(48, 48)
prediction:  [[1.8613468e-01 1.6142183e-04 8.9685336e-02 1.9945849e-02 3.6978683e-01
  1.9508504e-03 3.3233503e-01]]
Max:  0.1861346811056137
Max:  0.3697868287563324
index :  4
[15] (1,)
[15]
[ 23  93 595 373]
Crop Image:  (280, 572, 3)
(48, 48)
prediction:  [[3.9659643e-01 2.3988615e-04 2.9405331e-02 2.1123953e-02 3.5651478e-01
  7.8838738e-04 1.9533125e-01]]
Max:  0.39659643173217773
index :  0
[15] (1,)
[15]
[ 24  97 594 369]
Crop Image:  (272, 570, 3)
(48, 48)
prediction:  [[7.2109491e-01 6.2252856e-03 1.6125198e-

prediction:  [[0.06872278 0.00054857 0.16400127 0.11019055 0.47694376 0.03469187
  0.1449012 ]]
Max:  0.06872277706861496
Max:  0.16400127112865448
Max:  0.4769437611103058
index :  4
[15] (1,)
[15]
[ 28  97 588 369]
Crop Image:  (272, 560, 3)
(48, 48)
prediction:  [[0.07394058 0.00371023 0.17458029 0.12941776 0.40133807 0.06163526
  0.15537782]]
Max:  0.07394057512283325
Max:  0.17458029091358185
Max:  0.4013380706310272
index :  4
[15] (1,)
[15]
[ 32  97 584 369]
Crop Image:  (272, 552, 3)
(48, 48)
prediction:  [[0.03342842 0.00178103 0.10471057 0.22692302 0.4337991  0.02003409
  0.17932378]]
Max:  0.03342841565608978
Max:  0.10471057146787643
Max:  0.22692301869392395
Max:  0.4337990880012512
index :  4
[15] (1,)
[15]
[ 26  96 590 370]
Crop Image:  (274, 564, 3)
(48, 48)
prediction:  [[0.06288548 0.00206235 0.16812739 0.20498297 0.28897932 0.04427109
  0.2286914 ]]
Max:  0.06288547813892365
Max:  0.1681273877620697
Max:  0.2049829661846161
Max:  0.28897932171821594
index :  4
[15] (

[15] (1,)
[15]
[ 26  95 591 371]
Crop Image:  (276, 565, 3)
(48, 48)
prediction:  [[1.5520670e-01 1.1791577e-05 2.7707589e-01 6.0048439e-02 2.8639507e-01
  3.0386446e-02 1.9087562e-01]]
Max:  0.15520669519901276
Max:  0.2770758867263794
Max:  0.2863950729370117
index :  4
[15] (1,)
[15]
[ 27  95 590 371]
Crop Image:  (276, 563, 3)
(48, 48)
prediction:  [[1.9663449e-01 1.1152080e-05 2.7229366e-01 6.4828895e-02 2.8172997e-01
  2.7993737e-02 1.5650806e-01]]
Max:  0.19663448631763458
Max:  0.27229365706443787
Max:  0.28172996640205383
index :  4
[15] (1,)
[15]
[ 27  94 590 372]
Crop Image:  (278, 563, 3)
(48, 48)
prediction:  [[1.2678921e-01 2.1112251e-05 2.4746487e-01 8.8969402e-02 2.8078392e-01
  3.8034078e-02 2.1793748e-01]]
Max:  0.12678921222686768
Max:  0.2474648654460907
Max:  0.28078392148017883
index :  4
[15] (1,)
[15]
[ 34  93 584 373]
Crop Image:  (280, 550, 3)
(48, 48)
prediction:  [[2.54489064e-01 1.09928515e-04 1.01342998e-01 1.96143985e-01
  2.11956710e-01 6.28835941e-03 2.

[15] (1,)
[15]
[ 31  86 588 379]
Crop Image:  (293, 557, 3)
(48, 48)
prediction:  [[5.5555042e-02 8.9613923e-06 4.0735939e-01 2.6806314e-02 2.5547096e-01
  8.6256869e-02 1.6854241e-01]]
Max:  0.05555504187941551
Max:  0.40735939145088196
index :  2
[15] (1,)
[15]
[ 32  95 586 371]
Crop Image:  (276, 554, 3)
(48, 48)
prediction:  [[2.3022185e-01 7.4154610e-05 2.9255515e-01 7.7146858e-02 2.6542377e-01
  2.9472711e-02 1.0510557e-01]]
Max:  0.23022185266017914
Max:  0.29255515336990356
index :  2
[15] (1,)
[15]
[ 31  97 586 369]
Crop Image:  (272, 555, 3)
(48, 48)
prediction:  [[1.6838324e-01 3.6166322e-05 4.1632032e-01 8.0971584e-02 2.4082509e-01
  1.6857544e-02 7.6606043e-02]]
Max:  0.16838324069976807
Max:  0.4163203239440918
index :  2
[15] (1,)
[15]
[ 32  86 587 379]
Crop Image:  (293, 555, 3)
(48, 48)
prediction:  [[6.2159151e-02 2.2508204e-05 2.8840598e-01 3.8229015e-02 3.7499246e-01
  3.4724455e-02 2.0146655e-01]]
Max:  0.06215915083885193
Max:  0.28840598464012146
Max:  0.37499246

[15] (1,)
[15]
[ 94 103 518 368]
Crop Image:  (265, 424, 3)
(48, 48)
prediction:  [[0.26864976 0.00306094 0.1000732  0.05290992 0.27790293 0.2871773
  0.01022593]]
Max:  0.26864975690841675
Max:  0.2779029309749603
Max:  0.28717729449272156
index :  5
[15] (1,)
[15]
[104 118 512 349]
Crop Image:  (231, 408, 3)
(48, 48)
prediction:  [[3.3015442e-01 3.5230163e-04 6.6552968e-03 1.3105958e-02 5.9366888e-01
  2.5311867e-02 3.0751238e-02]]
Max:  0.3301544189453125
Max:  0.5936688780784607
index :  4
[15] (1,)
[15]
[125 118 455 354]
Crop Image:  (236, 330, 3)
(48, 48)
prediction:  [[0.08470181 0.0027486  0.09925622 0.17589024 0.27862984 0.01037617
  0.34839717]]
Max:  0.08470181375741959
Max:  0.09925622493028641
Max:  0.1758902370929718
Max:  0.2786298394203186
Max:  0.3483971655368805
index :  6
[15] (1,)
[15]
[ 96 113 521 354]
Crop Image:  (241, 425, 3)
(48, 48)
prediction:  [[3.9793000e-01 8.9083682e-05 4.4928111e-02 2.5291425e-01 1.4389886e-01
  1.2826355e-01 3.1976219e-02]]
Max:  0.3979

prediction:  [[3.9911470e-01 3.8504455e-05 3.3458418e-01 7.1344070e-02 1.4272065e-01
  1.1175219e-02 4.1022629e-02]]
Max:  0.3991146981716156
index :  0
[15] (1,)
[15]
[177 148 439 322]
Crop Image:  (174, 262, 3)
(48, 48)
prediction:  [[1.83335513e-01 1.03686783e-04 5.31681955e-01 1.18038282e-01
  1.21992014e-01 1.57574601e-02 2.90911477e-02]]
Max:  0.18333551287651062
Max:  0.5316819548606873
index :  2
[15] (1,)
[15]
[176 147 445 323]
Crop Image:  (176, 269, 3)
(48, 48)
prediction:  [[9.57878754e-02 1.82767162e-05 3.48662794e-01 1.03407033e-01
  3.42394888e-01 5.09538967e-03 1.04633704e-01]]
Max:  0.09578787535429001
Max:  0.348662793636322
index :  2
[15] (1,)
[15]
[181 147 439 323]
Crop Image:  (176, 258, 3)
(48, 48)
prediction:  [[3.5227421e-01 2.6196038e-04 1.8713029e-01 2.3268405e-01 1.2851049e-01
  2.4552705e-02 7.4586369e-02]]
Max:  0.35227420926094055
index :  0
[15] (1,)
[15]
[182 150 433 320]
Crop Image:  (170, 251, 3)
(48, 48)
prediction:  [[0.5577645  0.00335815 0.2866286

prediction:  [[1.0549851e-01 3.5573202e-04 6.5529801e-02 3.9596224e-01 2.3020722e-01
  1.9220823e-02 1.8322572e-01]]
Max:  0.10549850761890411
Max:  0.3959622383117676
index :  3
[15] (1,)
[15]
[183 144 435 326]
Crop Image:  (182, 252, 3)
(48, 48)
prediction:  [[0.34435153 0.00122962 0.08386118 0.37377712 0.07411101 0.0651115
  0.05755803]]
Max:  0.34435153007507324
Max:  0.3737771213054657
index :  3
[15] (1,)
[15]
[182 143 437 326]
Crop Image:  (183, 255, 3)
(48, 48)
prediction:  [[3.3148465e-01 1.4938424e-04 3.6420800e-02 3.0207187e-01 8.9438669e-02
  1.3580453e-01 1.0463015e-01]]
Max:  0.3314846456050873
index :  0
[15] (1,)
[15]
[181 145 436 325]
Crop Image:  (180, 255, 3)
(48, 48)
prediction:  [[1.79990977e-01 3.64154868e-04 6.90567121e-02 4.48756635e-01
  1.14042446e-01 6.66470826e-02 1.21141881e-01]]
Max:  0.1799909770488739
Max:  0.4487566351890564
index :  3
[15] (1,)
[15]
[181 147 438 323]
Crop Image:  (176, 257, 3)
(48, 48)
prediction:  [[2.0146552e-01 2.9748361e-04 1.03638

prediction:  [[3.3401000e-01 2.4275132e-04 1.1626816e-01 2.7718297e-01 1.3833785e-01
  5.5690754e-02 7.8267477e-02]]
Max:  0.3340100049972534
index :  0
[15] (1,)
[15]
[180 145 438 325]
Crop Image:  (180, 258, 3)
(48, 48)
prediction:  [[0.24212672 0.00048073 0.09680262 0.30641082 0.24224469 0.05358789
  0.05834653]]
Max:  0.2421267181634903
Max:  0.3064108192920685
index :  3
[15] (1,)
[15]
[179 147 442 323]
Crop Image:  (176, 263, 3)
(48, 48)
prediction:  [[6.1871789e-02 1.5934992e-04 9.6119203e-02 3.2572213e-01 2.3036687e-01
  1.2322240e-01 1.6253829e-01]]
Max:  0.061871789395809174
Max:  0.09611920267343521
Max:  0.3257221281528473
index :  3
[15] (1,)
[15]
[179 145 442 325]
Crop Image:  (180, 263, 3)
(48, 48)
prediction:  [[4.9005959e-02 6.2479849e-05 4.7952194e-02 4.6757779e-01 1.9692954e-01
  8.4932245e-02 1.5353978e-01]]
Max:  0.049005959182977676
Max:  0.4675777852535248
index :  3
[15] (1,)
[15]
[182 147 431 323]
Crop Image:  (176, 249, 3)
(48, 48)
prediction:  [[0.20053278 0.

prediction:  [[6.2443918e-01 3.2252360e-06 2.8584677e-01 3.6815491e-02 2.4595216e-02
  2.5788479e-02 2.5116359e-03]]
Max:  0.6244391798973083
index :  0
[15] (1,)
[15]
[171 162 451 309]
Crop Image:  (147, 280, 3)
(48, 48)
prediction:  [[1.6202423e-01 3.8301170e-07 6.5586829e-01 9.4790600e-02 3.9249614e-02
  3.1608991e-02 1.6457817e-02]]
Max:  0.16202422976493835
Max:  0.6558682918548584
index :  2
[15] (1,)
[15]
[169 164 442 309]
Crop Image:  (145, 273, 3)
(48, 48)
prediction:  [[7.26798102e-02 1.97967256e-06 1.42769888e-01 4.00004268e-01
  1.70103893e-01 1.02068439e-01 1.12371705e-01]]
Max:  0.07267981022596359
Max:  0.14276988804340363
Max:  0.4000042676925659
index :  3
[15] (1,)
[15]
[168 164 454 309]
Crop Image:  (145, 286, 3)
(48, 48)
prediction:  [[3.6700445e-01 1.3395227e-08 1.6694959e-01 1.5920103e-01 9.2548542e-02
  1.4739854e-02 1.9955660e-01]]
Max:  0.3670044541358948
index :  0
[15] (1,)
[15]
[167 173 411 307]
Crop Image:  (134, 244, 3)
(48, 48)
prediction:  [[5.1346060e-0

prediction:  [[2.0996344e-01 4.2120122e-05 6.6252895e-02 2.3399754e-01 1.7424409e-01
  4.4887919e-02 2.7061200e-01]]
Max:  0.20996344089508057
Max:  0.23399753868579865
Max:  0.2706120014190674
index :  6
[15] (1,)
[15]
[166 172 459 301]
Crop Image:  (129, 293, 3)
(48, 48)
prediction:  [[3.4034422e-01 1.5282448e-07 3.6665797e-01 3.3371601e-02 3.5466522e-02
  9.7354330e-02 1.2680519e-01]]
Max:  0.34034422039985657
Max:  0.36665797233581543
index :  2
[15] (1,)
[15]
[165 168 457 305]
Crop Image:  (137, 292, 3)
(48, 48)
prediction:  [[2.7403674e-01 7.9831725e-06 1.2926508e-01 1.4130938e-01 9.0456992e-02
  4.5620937e-02 3.1930289e-01]]
Max:  0.2740367352962494
Max:  0.31930288672447205
index :  6
[15] (1,)
[15]
[164 172 419 308]
Crop Image:  (136, 255, 3)
(48, 48)
prediction:  [[0.34000546 0.00055717 0.07637129 0.47539818 0.083079   0.00438921
  0.02019964]]
Max:  0.34000545740127563
Max:  0.4753981828689575
index :  3
[15] (1,)
[15]
[166 172 449 301]
Crop Image:  (129, 283, 3)
(48, 48)
pr

prediction:  [[0.1269353  0.00063792 0.14190553 0.49032536 0.11182564 0.03453402
  0.09383614]]
Max:  0.12693530321121216
Max:  0.1419055312871933
Max:  0.49032536149024963
index :  3
[15] (1,)
[15]
[164 167 458 306]
Crop Image:  (139, 294, 3)
(48, 48)
prediction:  [[6.8451956e-02 1.3403518e-05 1.1176940e-01 2.0908782e-01 1.4635164e-01
  5.3790640e-02 4.1053513e-01]]
Max:  0.06845195591449738
Max:  0.11176940053701401
Max:  0.2090878188610077
Max:  0.41053512692451477
index :  6
[15] (1,)
[15]
[165 170 455 303]
Crop Image:  (133, 290, 3)
(48, 48)
prediction:  [[7.5196542e-02 1.7651208e-05 1.3484155e-01 2.6418170e-01 1.2759915e-01
  5.2057859e-02 3.4610546e-01]]
Max:  0.07519654184579849
Max:  0.13484154641628265
Max:  0.2641817033290863
Max:  0.3461054563522339
index :  6
[15] (1,)
[15]
[165 168 451 305]
Crop Image:  (137, 286, 3)
(48, 48)
prediction:  [[2.6204211e-01 8.6042448e-05 6.8474673e-02 1.5207148e-01 7.1426302e-02
  1.6440226e-01 2.8149709e-01]]
Max:  0.2620421051979065
Max:  

[15] (1,)
[15]
[161 172 424 308]
Crop Image:  (136, 263, 3)
(48, 48)
prediction:  [[7.5979628e-02 1.4029515e-04 3.8270764e-02 8.1354421e-01 4.4579946e-02
  1.6339833e-02 1.1145369e-02]]
Max:  0.07597962766885757
Max:  0.8135442137718201
index :  3
[15] (1,)
[15]
[168 170 448 303]
Crop Image:  (133, 280, 3)
(48, 48)
prediction:  [[2.7961415e-01 4.5874098e-05 9.1425218e-02 3.1953424e-02 1.8329239e-01
  2.0582981e-01 2.0783910e-01]]
Max:  0.2796141505241394
index :  0
[15] (1,)
[15]
[162 172 461 302]
Crop Image:  (130, 299, 3)
(48, 48)
prediction:  [[1.6625805e-01 1.2184357e-06 1.4864340e-01 7.2941601e-02 1.2059675e-01
  8.6327761e-02 4.0523127e-01]]
Max:  0.1662580519914627
Max:  0.4052312672138214
index :  6
[15] (1,)
[15]
[169 168 444 305]
Crop Image:  (137, 275, 3)
(48, 48)
prediction:  [[2.2362183e-01 1.0052188e-06 4.6275843e-02 2.9303992e-02 3.5147727e-01
  2.4711886e-02 3.2460818e-01]]
Max:  0.22362183034420013
Max:  0.3514772653579712
index :  4
[15] (1,)
[15]
[164 174 456 300]
Cr